language: python
python:
  - 2.7
  - 3.5
  - 3.6
sudo: true
services:
  - docker
script:
  - /usr/bin/true
deploy:
  - provider: pypi
    user: $PYPI_USER
    password: $PYPI_PASSWORD
    on:
      all_branches: true
      tags: true
      python: 2.7
    skip_cleanup: true
